# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])
a1

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],
             [4,5,6]])
a2

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],
             [4,5,6]],
            [[7,8,9],
             [10,11,12]] ])
a1,a2,a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype

((3,), 1, dtype('int64'))

In [8]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype

((2, 3), 2, dtype('int64'))

In [9]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.dtype

((2, 2, 3), 3, dtype('int64'))

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [12]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
rArray=np.arange(0,100,3)
rArray

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ranArray=np.random.randint(0,10,size=(7,2))
ranArray

array([[9, 2],
       [8, 5],
       [1, 6],
       [5, 6],
       [4, 9],
       [3, 3],
       [7, 7]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ranFloArray=np.random.random((3,5))
ranFloArray

array([[0.02541539, 0.85866189, 0.3084985 , 0.12596809, 0.91774357],
       [0.87450344, 0.79863408, 0.53157862, 0.38385466, 0.06754117],
       [0.36148238, 0.11915485, 0.65621927, 0.48603735, 0.54870476]])

In [21]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
randomArray=np.random.randint(10,size=(4,6))
randomArray

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [25]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randomArray2=np.random.randint(10,size=(3,7))


# Find the unique numbers in the array you just created
randomArray2,np.unique(randomArray2)

(array([[4, 1, 4, 7, 9, 8, 8],
        [0, 8, 6, 8, 7, 0, 7],
        [7, 2, 0, 7, 2, 2, 0]]),
 array([0, 1, 2, 4, 6, 7, 8, 9]))

In [26]:
# Find the 0'th index of the latest array you created
randomArray2[0]

array([4, 1, 4, 7, 9, 8, 8])

In [29]:
# Get the first 2 rows of latest array you created
randomArray2[:2]

array([[4, 1, 4, 7, 9, 8, 8],
       [0, 8, 6, 8, 7, 0, 7]])

In [31]:
# Get the first 2 values of the first 2 rows of the latest array
randomArray2[:2,:2]

array([[4, 1],
       [0, 8]])

In [34]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1=np.random.randint(10,size=(3,5))
arr2=np.random.randint(10,size=(3,5))
arr1,arr2

(array([[2, 6, 0, 3, 3],
        [4, 6, 6, 3, 6],
        [2, 5, 1, 9, 8]]),
 array([[4, 5, 3, 9, 6],
        [8, 6, 0, 0, 8],
        [8, 3, 8, 2, 6]]))

In [38]:
# Add the two arrays together
arr3=arr1+arr2
arr1,arr2,arr3

(array([[2, 6, 0, 3, 3],
        [4, 6, 6, 3, 6],
        [2, 5, 1, 9, 8]]),
 array([[4, 5, 3, 9, 6],
        [8, 6, 0, 0, 8],
        [8, 3, 8, 2, 6]]),
 array([[ 6, 11,  3, 12,  9],
        [12, 12,  6,  3, 14],
        [10,  8,  9, 11, 14]]))

In [40]:
# Create another array of ones of shape (5, 3)
ones=np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
# Try add the array of ones and the other most recent array together
resArr=ones+ arr1
resArr

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [61]:
# Create another array of ones of shape (3, 5)
resArr=ones+ arr1.T
resArr

array([[ 3.,  5.,  3.],
       [ 7.,  7.,  6.],
       [ 1.,  7.,  2.],
       [ 4.,  4., 10.],
       [ 4.,  7.,  9.]])

In [62]:
# Subtract the new array of ones from the other most recent array
resArr=resArr-ones
resArr

array([[2., 4., 2.],
       [6., 6., 5.],
       [0., 6., 1.],
       [3., 3., 9.],
       [3., 6., 8.]])

In [63]:
# Multiply the ones array with the latest array
resArr=resArr*ones
resArr

array([[2., 4., 2.],
       [6., 6., 5.],
       [0., 6., 1.],
       [3., 3., 9.],
       [3., 6., 8.]])

In [64]:
# Take the latest array to the power of 2 using '**'
resArr=resArr**2
resArr

array([[ 4., 16.,  4.],
       [36., 36., 25.],
       [ 0., 36.,  1.],
       [ 9.,  9., 81.],
       [ 9., 36., 64.]])

In [65]:
# Do the same thing with np.square()
resArr=np.square(resArr)
resArr

array([[1.600e+01, 2.560e+02, 1.600e+01],
       [1.296e+03, 1.296e+03, 6.250e+02],
       [0.000e+00, 1.296e+03, 1.000e+00],
       [8.100e+01, 8.100e+01, 6.561e+03],
       [8.100e+01, 1.296e+03, 4.096e+03]])

In [58]:
# Find the mean of the latest array using np.mean()
mean=np.mean(resArr)
mean

0.0

In [66]:
# Find the maximum of the latest array using np.max()
mean=np.max(resArr)
mean

6561.0

In [69]:
# Find the minimum of the latest array using np.min()
maximum=np.min(resArr)
maximum

0.0

In [70]:
# Find the standard deviation of the latest array
minimum=np.std(resArr)
minimum

1784.313582305532

In [71]:
# Find the variance of the latest array
minimum=np.var(resArr)
minimum

3183774.960000001

In [73]:
# Reshape the latest array to (3, 5, 1)
resArr=resArr.reshape(3, 5, 1)
resArr

array([[[1.600e+01],
        [2.560e+02],
        [1.600e+01],
        [1.296e+03],
        [1.296e+03]],

       [[6.250e+02],
        [0.000e+00],
        [1.296e+03],
        [1.000e+00],
        [8.100e+01]],

       [[8.100e+01],
        [6.561e+03],
        [8.100e+01],
        [1.296e+03],
        [4.096e+03]]])

In [74]:
# Transpose the latest array
resArr=resArr.T
resArr

array([[[1.600e+01, 6.250e+02, 8.100e+01],
        [2.560e+02, 0.000e+00, 6.561e+03],
        [1.600e+01, 1.296e+03, 8.100e+01],
        [1.296e+03, 1.000e+00, 1.296e+03],
        [1.296e+03, 8.100e+01, 4.096e+03]]])

What does the transpose do?

In [75]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

In [76]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1, mat2)

array([[12, 37],
       [24, 18],
       [ 7, 35]])

In [77]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))

In [78]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3, mat4)

ValueError: ignored

It doesn't work. How would you fix it?

In [79]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(mat3.T, mat4)

array([[58, 13, 63],
       [77, 18, 89],
       [52, 23, 77]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [80]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
mat5 = np.random.randint(10, size=(4, 2))
mat6 = np.random.randint(10, size=(4, 2))

In [82]:
# Compare the two arrays with '>'
mat5 > mat6

array([[False,  True],
       [ True, False],
       [ True, False],
       [ True, False]])

What happens when you compare the arrays with `>`?

In [83]:
# Compare the two arrays with '>='
mat5 >= mat6

array([[False,  True],
       [ True, False],
       [ True, False],
       [ True, False]])

In [84]:
# Find which elements of the first array are greater than 7
mat5 > 7

array([[False, False],
       [ True, False],
       [False, False],
       [False, False]])

In [86]:
# Which parts of each array are equal? (try using '==')
mat5 == mat6

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [87]:
# Sort one of the arrays you just created in ascending order
np.sort(mat5)

array([[2, 3],
       [2, 9],
       [2, 3],
       [3, 6]])

In [89]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat6),mat6

(array([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1]]),
 array([[8, 0],
        [7, 6],
        [1, 7],
        [0, 8]]))

In [90]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat5)

2

In [91]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat6)

1

In [93]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(mat5, axis=1),mat5

(array([0, 0, 1, 0]),
 array([[3, 2],
        [9, 2],
        [2, 3],
        [6, 3]]))

In [95]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(mat6, axis=0),mat6

(array([0, 3]),
 array([[8, 0],
        [7, 6],
        [1, 7],
        [0, 8]]))

In [98]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-1.36987106, -0.77178075,  0.87867355, -0.23959451,  1.20938197],
       [ 0.53796   ,  2.73442216,  0.09376543, -1.40640527, -0.03452966],
       [-0.96301563,  0.97718   ,  0.04198006, -0.13727182, -0.12413239]])

In [99]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.